version: "3.7"

services:
  challenge:
    image: ghcr.io/cybermouflons/ccsc2024/tlv:latest
    restart: always
    ports:
      - 8080:8080
    build:
      context: ./setup
      dockerfile: Dockerfile
      labels: 
        ctf.challenge.name: TLV